run:
	go run cmd/main.go

create_DC:
	docker run --name=TestTodo -e POSTGRES_PASSWORD="postgres" -p 5436:5432 -d postgres

migrate_create:
	migrate create -ext sql -dir ./migrations -seq init

migrate_up:
	migrate -path ./migrations -database 'postgres://postgres:postgres@localhost:5436/postgres?sslmode=disable' up

migrate_down:
	migrate -path ./migrations -database 'postgres://postgres:postgres@localhost:5436/postgres?sslmode=disable' down